repositories:
  - name: aws
    url: 489994096722.dkr.ecr.us-east-1.amazonaws.com
    username: AWS
    oci: true

environments:
  dev:
    values:
      - namespace: compulse-360
  stg:
    values:
      - namespace: compulse-360
  prod:
    values:
      - namespace: compulse-360

releases:
  - name: compulse-360
    namespace: "{{ .Values.namespace }}"
    labels:
      app: compulse-360
    wait: true
    chart: aws/deployments
    version: 1.0.7
    values:
      - envs/{{ .Environment.Name }}/values/compulse-360-values.yaml
      - envs/{{ .Environment.Name }}/values/global-values.yaml
    # secrets:
    #   - envs/{{ .Environment.Name }}/secrets.yaml
  - name: compulse-360-ingress
    namespace: "{{ .Values.namespace }}"
    labels:
      app: compulse-360-ingress
    wait: true
    chart: aws/ingress-helm-charts
    version: 1.0.2
    values:
      - envs/{{ .Environment.Name }}/values/ingress-values.yaml
