ENVIRONMENT: dev
DEPLOY_APP: sinclair
DEPLOYMENTS:
  sinclair:
    NAME: "sinclair"

### You can change environment variables below
    ENV:
      ENVIRONMENT: "{{ .Values.GLOBAL.ENVIRONMENT }}"
      NAMESPACE: "{{ .Values.GLOBAL.NAMESPACE }}"

### DevOps things below
    REPLICAS: 2
    RESOURCES:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    PORTS:
    - name: sinclair
      containerPort: 80
      protocol: TCP
    SERVICE_PORTS:
    - name: sinclair
      port: 80
      targetPort: 80
    # START_COMMAND: 
    # - supervisord
    # ARGS:
    # - -n
    # MIGRATIONS_ARGS:
    # - python manage_custom.py migrate 2>&1
    LIVENESS_PROBE:
      httpGet:
        path: /api/health
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 10
    READINESS_PROBE:
      httpGet:
        path: /api/health
        port: 80
      timeoutSeconds: 10
      periodSeconds: 5
      successThreshold: 2
      failureThreshold: 1
