ENVIRONMENT: stg
DEPLOY_APP: compulse-360-ingress
INGRESS:
  compulse-360-ingress:
    NAME: compulse-360-ingress
    NAMESPACE: compulse-360
    ANNOTATIONS: # map with annotations https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/tags: environment=stg
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/security-groups: sg-00b2950025a7bf227,sg-00e292084ae11689e # default,public web
      alb.ingress.kubernetes.io/subnets: subnet-03ae9733f09a87cc7,subnet-0b9b70a8800911bce,subnet-0e420b8a89ef9b928 #Public subnets of eks vpc separated by ,
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:681420559112:certificate/5788f2a3-a491-458e-b539-b749cf4a3590,arn:aws:acm:us-east-1:681420559112:certificate/17cdf51c-a921-4c02-aee4-161d3177e1aa,arn:aws:acm:us-east-1:681420559112:certificate/76ae359c-0195-40ef-9177-4234956b33c5,arn:aws:acm:us-east-1:681420559112:certificate/aff1f4b9-3aec-4d68-9246-94cb187c277e
      alb.ingress.kubernetes.io/group.name: external
      service.beta.kubernetes.io/aws-load-balancer-name: k8s-stg-external
    RULES:
    - host: compulse360.stg.adportal.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ssl-redirect
              port:
                name: use-annotation
        - path: /
          pathType: Prefix
          backend:
            service:
              name: compulse-360
              port:
                number: 80
