name: Deploy story book

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - DEVOPS-*
    paths:
      - ui/vue2/**

jobs:
  deploy_story_book:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ui/vue2

    steps:
      - uses: actions/checkout@v3

      - uses: chrislennon/action-aws-cli@v1.1

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Yarn install dependencies 📦
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
          dir: "ui/vue2"

      - name: Build storybook ⚙️
        uses: borales/actions-yarn@v4
        with:
          cmd: storybook:build
          dir: "ui/vue2"

      - name: Show files
        run: |
          ls -la

      - name: Upload static
        run: |
          aws s3 sync storybook-static s3://compulse360-storybook/ --no-progress --follow-symlinks --delete
