name: My Workflow
on:
  workflow_dispatch:
    inputs:
      namespaces:
        type: string
        description: Namespaces for deploy
        default: '["admanager-sbg","admanager-lpp"]'
        required: true

  push:
    branches: [main]

env:
  NAMESPACES: ${{ inputs.namespaces || '["admanager-sbg","admanager-lpp"]' }}
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My step
        run: echo "My namespace is ${{ env.NAMESPACES }}"
