name: My Workflow
on:
  workflow_dispatch:

  push:
    branches: [main]

env:
  NAMESPACES: ${{ matrix.namespace }}
jobs:
  my-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        namespace: [sbg, 360i]
    steps:
      - name: My step
        run: echo "My namespace is ${{ env.NAMESPACES }}"
