name: Example Workflow
on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          source test-repo-compulse360/ci-configs/envs/dev/test.txt
          echo "Namespace=${VITE_APPLICATION_TYPE}"
          echo "::set-env name=NAMESPACE::${VITE_APPLICATION_TYPE}"
      - name: Print environment variables
        run: |
          echo "Namespace=${NAMESPACE}"
