name: Delete Orphaned PRs Argo Applications

on:
  workflow_dispatch:
    inputs:
      PR_NUMBER:
        description: 'Enter the PR number to process'
        required: true
        type: string
        default: '123'  # Example default PR number, can be updated or left blank
      service:
        description: 'Name of the service'
        required: true
        default: 'visit-view'

jobs:
  trigger-argo-app-deletion:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Argo app delete
        id: app-del
        run: | 
            echo ${{ github.event.inputs.service }}
            echo ${{ github.event.inputs.PR_NUMBER }}
        # uses: DexCare/common/.github/workflows/reusable-argo-app-delete.yaml@INFRA-asasas/saasasa
        # with:
        #   SERVICE: ${{ github.event.inputs.service }}
        #   PR_NUMBER: ${{ github.event.inputs.PR_NUMBER }}
        # secrets:
        #   ARGO_CD_FROSH_TOKEN: ${{ secrets.ARGO_CD_FROSH_TOKEN }}
