name: My Workflow
on:
  workflow_dispatch:

jobs:
  my-job:
    strategy:
      matrix:
        namespace: [sbg, 360i]
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: |
          echo "The namespace value is ${matrix.namespace}"
