name: Build and deploy PR application
on:
  pull_request:
    branches: [main]

jobs:
  test-run:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
        - name: Test PR run
          run: |
            echo "Kesa dia???"

      