name:  App Workflow

on:
    workflow_dispatch:
    inputs:
        PR_NUMBER:
        description: 'Enter the PR number to process'
        required: true
        type: string
        default: '123'  # Example default PR number, can be updated or left blank
        branch:
        description: 'Branch name for reference'
        required: true
        default: 'test-pr'
        service:
        description: 'Name of the service'
        required: true
        default: 'visit-view'

jobs:
    trigger-argo-app-deletion:
        runs-on: ubuntu-latest
        steps:
          - name: Trigger Argo app delete
            id: check-pr
            run: |
                  echo ${{ github.event.inputs.service }}
                  echo ${{ github.event.inputs.PR_NUMBER }}
        # uses: DexCare/common/.github/workflows/reusable-argo-app-delete.yaml@INFRA-asasas/saasasa
        # with:
        #   SERVICE: visit-view
        #   PR_NUMBER: ${{ matrix.pr.PR_NUMBER }}
        # secrets:
        #   ARGO_CD_FROSH_TOKEN: ${{ secrets.ARGO_CD_FROSH_TOKEN }}
